language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "10"
deploy:
  provider: script
  script: yarn install && yarn run deploy
  github_token: $GH_TOKEN
  cleanup: false
  on:
    branch: master
