language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "10"
script:
  - gatsby build --prefix-paths
deploy:
  provider: pages
  # Note: change "docs" to the directory where your gatsby-site lives, if necessary
  script: yarn install && yarn run deploy
  cleanup: false
  github_token: $GH_TOKEN
  local_dir: build
  on:
    branch: master
